tbl_profession = {
                    ["Bard"]  = {
                                 ["root"]            = {["skill"]   = "Busking",         ["stat"]    = "EMP"},
                                 ["ability"]         = {["branch1"] = "The Charmer",     ["branch2"] = "The Informant",    ["branch3"] = "The Manipulator"},
                                 ["The Charmer"]     = {["skill1"]  = "Return Act",      ["stat1"]   = "EMP",
                                                        ["skill2"]  = "Raise A Crowd",   ["stat2"]   = "EMP",
                                                        ["skill3"]  = "Good Friend",     ["stat3"]   = "EMP"},
                                 ["The Informant"]   = {["skill1"]  = "Fade",            ["stat1"]   = "INT",
                                                        ["skill2"]  = "Spread The Word", ["stat2"]   = "INT",
                                                        ["skill3"]  = "Acclimatize",     ["stat3"]   = "INT"},
                                 ["The Manipulator"] = {["skill1"]  = "Poison The Well", ["stat1"]   = "EMP",
                                                        ["skill2"]  = "Needling",        ["stat2"]   = "EMP",
                                                        ["skill3"]  = "Et Tu Brute",     ["stat3"]   = "EMP"},
                                },
                                
                    ["Craftsman"] = {
                                 ["root"]            = {["skill"]   = "Patch Job",              ["stat"]    = "CRA"},
                                 ["ability"]         = {["branch1"] = "The forge Master",       ["branch2"] = "The Alchemist",    ["branch3"] = "The Improviser"},
                                 ["The forge Master"]= {["skill1"]  = "Extensive Catalogue",    ["stat1"]   = "INT",
                                                        ["skill2"]  = "Journeyman",             ["stat2"]   = "CRA",
                                                        ["skill3"]  = "Master Crafting",        ["stat3"]   = "CRA"},
                                 ["The Alchemist"]   = {["skill1"]  = "Mental Pharmacy",        ["stat1"]   = "INT",
                                                        ["skill2"]  = "Double Dose",            ["stat2"]   = "CRA",
                                                        ["skill3"]  = "Adaptation",             ["stat3"]   = "CRA"},
                                 ["The Improviser"]  = {["skill1"]  = "Augmentation",           ["stat1"]   = "CRA",
                                                        ["skill2"]  = "Silver Coating",         ["stat2"]   = "CRA",
                                                        ["skill3"]  = "Pinpoint",               ["stat3"]   = "CRA"},
                                },

                    ["Criminal"] = {
                                 ["root"]            = {["skill"]   = "Practiced Paranoia",     ["stat"]    = "INT"},
                                 ["ability"]         = {["branch1"] = "The Thief",              ["branch2"] = "The Gang Boss",    ["branch3"] = "The Assassin"},
                                 ["The Thief"]       = {["skill1"]  = "Case The Area",          ["stat1"]   = "INT",
                                                        ["skill2"]  = "Mental Key",             ["stat2"]   = "INT",
                                                        ["skill3"]  = "Go To Ground",           ["stat3"]   = "INT"},
                                 ["The Gang Boss"]   = {["skill1"]  = "Weak Spot",              ["stat1"]   = "EMP",
                                                        ["skill2"]  = "Marked Man",             ["stat2"]   = "WIL",
                                                        ["skill3"]  = "Rally",                  ["stat3"]   = "WIL"},
                                 ["The Assassin"]    = {["skill1"]  = "Careful Aim",            ["stat1"]   = "DEX",
                                                        ["skill2"]  = "Eye Gouge",              ["stat2"]   = "DEX",
                                                        ["skill3"]  = "Assassin’s Strike",      ["stat3"]   = "DEX"},
                                },
                                
                    ["Doctor"] = {
                                 ["root"]            = {["skill"]   = "Healing Hands",          ["stat"]    = "CRA"},
                                 ["ability"]         = {["branch1"] = "The Surgeon",            ["branch2"] = "The Herbalist",    ["branch3"] = "The Anatomist"},
                                 ["The Surgeon"]     = {["skill1"]  = "Diagnose",               ["stat1"]   = "INT",
                                                        ["skill2"]  = "Analysis",               ["stat2"]   = "INT",
                                                        ["skill3"]  = "Effective Surgery",      ["stat3"]   = "CRA"},
                                 ["The Herbalist"]   = {["skill1"]  = "Healing Tent",           ["stat1"]   = "CRA",
                                                        ["skill2"]  = "Improvisation",          ["stat2"]   = "INT",
                                                        ["skill3"]  = "Herbal Remedy",          ["stat3"]   = "CRA"},
                                 ["The Anatomist"]   = {["skill1"]  = "Bleeding Wound",         ["stat1"]   = "INT",
                                                        ["skill2"]  = "Practical Carnage",      ["stat2"]   = "INT",
                                                        ["skill3"]  = "Crippling Wound",        ["stat3"]   = "INT"},
                                },

                    ["Mage"] = {
                                 ["root"]            = {["skill"]   = "Magical Training",       ["stat"]    = "INT"},
                                 ["ability"]         = {["branch1"] = "The Politician",         ["branch2"] = "The Scientist",    ["branch3"] = "The Arch Mage"},
                                 ["The Politician"]  = {["skill1"]  = "Scheming",               ["stat1"]   = "INT",
                                                        ["skill2"]  = "Grape Vine",             ["stat2"]   = "INT",
                                                        ["skill3"]  = "Assets",                 ["stat3"]   = "INT"},
                                 ["The Scientist"]   = {["skill1"]  = "Reverse Engineer",       ["stat1"]   = "INT",
                                                        ["skill2"]  = "Distillation",           ["stat2"]   = "CRA",
                                                        ["skill3"]  = "Mutate",                 ["stat3"]   = "INT"},
                                 ["The Arch Mage"]   = {["skill1"]  = "In Touch",               ["stat1"]   = "",
                                                        ["skill2"]  = "Immutable",              ["stat2"]   = "WIL",
                                                        ["skill3"]  = "Expanded Magic",         ["stat3"]   = "WIL"},
                                },

                    ["Man At Arms"] = {
                                 ["root"]            = {["skill"]   = "Tough As Nails",         ["stat"]    = "BOD"},
                                 ["ability"]         = {["branch1"] = "The Marksman",           ["branch2"] = "The Bounty Hunter",    ["branch3"] = "The Reaver"},
                                 ["The Marksman"]    = {["skill1"]  = "Extreme Range",          ["stat1"]   = "DEX",
                                                        ["skill2"]  = "Twin Shot",              ["stat2"]   = "DEX",
                                                        ["skill3"]  = "Pin Point Aim",          ["stat3"]   = "DEX"},
                                 ["The Bounty Hunter"]={["skill1"]  = "Bloodhound",             ["stat1"]   = "INT",
                                                        ["skill2"]  = "Booby Trap",             ["stat2"]   = "CRA",
                                                        ["skill3"]  = "Tactical Awareness",     ["stat3"]   = "INT"},
                                 ["The Reaver"]      = {["skill1"]  = "Fury",                   ["stat1"]   = "WIL",
                                                        ["skill2"]  = "Zweihand",               ["stat2"]   = "BOD",
                                                        ["skill3"]  = "Shrug It Off",           ["stat3"]   = "BOD"},
                                },

                    ["Merchant"] = {
                                 ["root"]            = {["skill"]   = "Well Traveled",          ["stat"]    = "INT"},
                                 ["ability"]         = {["branch1"] = "The Broker",             ["branch2"] = "The Contact",    ["branch3"] = "The Havekar"},
                                 ["The Broker"]      = {["skill1"]  = "Options",                ["stat1"]   = "INT",
                                                        ["skill2"]  = "Hard Bargain",           ["stat2"]   = "EMP",
                                                        ["skill3"]  = "Promise",                ["stat3"]   = "EMP"},
                                 ["The Contact"]      ={["skill1"]  = "Rookery",                ["stat1"]   = "EMP",
                                                        ["skill2"]  = "Insider",                ["stat2"]   = "INT",
                                                        ["skill3"]  = "Treasure Map",           ["stat3"]   = "INT"},
                                 ["The Havekar"]     = {["skill1"]  = "Well Connected",         ["stat1"]   = "WIL",
                                                        ["skill2"]  = "Fence",                  ["stat2"]   = "INT",
                                                        ["skill3"]  = "Warrior’s Debt",         ["stat3"]   = "EMP"},
                                },

                    ["Priest"] = {
                                 ["root"]            = {["skill"]   = "Initiate of the Gods",   ["stat"]    = "EMP"},
                                 ["ability"]         = {["branch1"] = "The Preacher",           ["branch2"] = "The Druid",    ["branch3"] = "The Fanatic"},
                                 ["The Preacher"]    = {["skill1"]  = "Divine Power",           ["stat1"]   = "",
                                                        ["skill2"]  = "Divine Authority",       ["stat2"]   = "EMP",
                                                        ["skill3"]  = "Precognition",           ["stat3"]   = "WIL"},
                                 ["The Druid"]        ={["skill1"]  = "Nature Attunement",      ["stat1"]   = "",
                                                        ["skill2"]  = "Read Nature",            ["stat2"]   = "INT",
                                                        ["skill3"]  = "Animal Compact",         ["stat3"]   = "WIL"},
                                 ["The Fanatic"]     = {["skill1"]  = "Blood Rituals",          ["stat1"]   = "WIL",
                                                        ["skill2"]  = "Fervor",                 ["stat2"]   = "EMP",
                                                        ["skill3"]  = "Word of God",            ["stat3"]   = "EMP"},
                                },

                    ["Witcher"] = {
                                 ["root"]            = {["skill"]   = "Witcher Training",       ["stat"]    = "INT"},
                                 ["ability"]         = {["branch1"] = "The Spellsword",         ["branch2"] = "The Mutant",    ["branch3"] = "The Slayer"},
                                 ["The Spellsword"]  = {["skill1"]  = "Meditation",             ["stat1"]   = "",
                                                        ["skill2"]  = "Magical Source",         ["stat2"]   = "",
                                                        ["skill3"]  = "Heliotrope",             ["stat3"]   = "WIL"},
                                 ["The Mutant"]       ={["skill1"]  = "Iron Stomach",           ["stat1"]   = "",
                                                        ["skill2"]  = "Frenzy",                 ["stat2"]   = "",
                                                        ["skill3"]  = "Transmutation",          ["stat3"]   = "BOD"},
                                 ["The Slayer"]      = {["skill1"]  = "Parry Arrows",           ["stat1"]   = "DEX",
                                                        ["skill2"]  = "Quick Strike",           ["stat2"]   = "REF",
                                                        ["skill3"]  = "Whirl",                  ["stat3"]   = "REF"},
                                },

                 };