tbl_skills_root = {"Body Skills", "Craft Skills", "Dexterity Skills", "Empathy Skills", "Intelligence Skills", "Reflex Skills", "Will Skills"};

tbl_skills = {
                    ["Body Skills"]  = {
                                         "Physique",
                                         "Endurance"
                                         },
                    ["Craft Skills"]  = {
                                         "Alchemy",
                                         "Crafting",
                                         "Disguise",
                                         "First Aid",
                                         "Forgery",
                                         "Pick Lock",
                                         "Trap Crafting"
                                         },
                    ["Dexterity Skills"]  = {
                                         "Archery",
                                         "Athletics",
                                         "Crossbow",
                                         "Sleigh of Hand",
                                         "Stealth"
                                         },
                    ["Empathy Skills"]  = {
                                         "Charisma",
                                         "Deceit",
                                         "Fine Arts",
                                         "Gambling",
                                         "Grooming and Style",
                                         "Human Perception",
                                         "Leadership",
                                         "Persuasion",
                                         "Performance",
                                         "Seduction"
                                         },
                    ["Intelligence Skills"]  = {
                                         "Awareness",
                                         "Business",
                                         "Deduction",
                                         "Education",
                                         "Common Speech",
                                         "Elder Speech",
                                         "Dwarven",
                                         "Monster Lore",
                                         "Social Etiquette",
                                         "Streetwise",
                                         "Tactics",
                                         "Teaching",
                                         "Wilderness Survival"
                                         },
                    ["Reflex Skills"]  = {
                                         "Brawling",
                                         "Dodge/Escape",
                                         "Melee",
                                         "Riding",
                                         "Sailing",
                                         "Small Blades",
                                         "Staff/Spear",
                                         "Swordmanship"
                                         },
                    ["Will Skills"]  = {
                                         "Courage",
                                         "Hex Weaving",
                                         "Intimidation",
                                         "Spell Casting",
                                         "Resist Magic",
                                         "Resist Coercion",
                                         "Ritual Crafting"
                                         },
                 };

-- flat skill list : [id] = stat, isDoubleIp, isArmorImpacted, class_skill_for                 
tbl_flat_skills = {
    physique = {"body", false, false, "Craftsman|Man At Arms"},
    endurance = {"body", false, false, "Craftsman"},
    alchemy = {"crafting", true, false, "Craftsman|Doctor|Witcher"},
    crafting = {"crafting", true, false, "Craftsman"},
    disguise = {"crafting", false, false, ""},
    firstAid = {"crafting", false, false, "Priest"},
    forgery = {"crafting", false, false,"Criminal"},
    pickLock = {"crafting", false, false,"Criminal"},
    trapCrafting = {"crafting", true, false, ""},
    archery = {"dexterity", false, true, "Man At Arms"},
    athletics = {"dexterity", false, true, "Craftsman|Criminal|Witcher"},
    crossbow = {"dexterity", false, true, "Man At Arms"},
    sleighOfHand = {"dexterity", false, true, "Criminal"},
    stealth = {"dexterity", false, true, "Criminal|Witcher"},
    charisma = {"empathy", false, false, "Bard|Doctor|Merchant|Priest"},
    deceit = {"empathy", false, false, "Bard|Criminal"},
    fineArts = {"empathy", false, false, "Craftsman|Bard"},
    gambling = {"empathy", false, false, "Merchant"},
    groomingAndStyle = {"empathy", false, false, "Mage"},
    humanPerception = {"empathy", false, false, "Bard|Doctor|Mage|Merchant|Priest"},
    leadership = {"empathy", false, false, "Priest"},
    persuasion = {"empathy", false, false, "Craftsman|Bard|Merchant"},
    performance = {"empathy", false, false, "Bard"},
    seduction = {"empathy", false, false, "Bard|Mage"},
    awareness = {"intelligence", false, false, "Criminal|Witcher"},
    business = {"intelligence", false, false, "Craftsman|Doctor|Merchant"},
    deduction = {"intelligence", false, false, "Doctor|Witcher"},
    education = {"intelligence", false, false, "Craftsman|Mage|Merchant"},
    commonSpeech = {"intelligence", true, false, "Bard|Merchant"},
    elderSpeech = {"intelligence", true, false, "Bard|Merchant"},
    dwarven = {"intelligence", true, false, "Bard|Merchant"},
    monsterLore = {"intelligence", true, false, ""},
    socialEtiquette = {"intelligence", false, false, "Bard|Doctor|Mage"},
    streetwise = {"intelligence", false, false, "Craftsman|Bard|Criminal|Merchant"},
    tactics = {"intelligence", true, false, ""},
    teaching = {"intelligence", false, false, "Priest"},
    wildernessSurvival = {"intelligence", false, false, "Doctor|Man At Arms|Priest|Witcher"},
    brawling = {"reflex", false, true, "Man At Arms"},
    dodgeEscape = {"reflex", false, true, "Man At Arms|Witcher"},
    melee = {"reflex", false, true, "Man At Arms"},
    riding = {"reflex", false, true,"Witcher"},
    sailing = {"reflex", false, true, ""},
    smallBlades = {"reflex", false, true, "Criminal|Doctor|Man At Arms|Merchant"},
    staffSpear = {"reflex", false, true, "Man At Arms|Mage"},
    swordmanship = {"reflex", false, true, "Man At Arms|Witcher"},
    courage = {"will", false, false, "Doctor|Man At Arms|Priest"},
    hexWeaving = {"will", true, true, "Mage|Priest"},
    intimidation = {"will", false, false,"Criminal|Man At Arms"},
    spellCasting = {"will", true, true, "Mage|Priest|Witcher"},
    resistMagic = {"will", true, false, "Mage"},
    resistCoercion = {"will", false, false, "Doctor|Merchant"},
    ritualCrafting = {"will", true, true, "Mage|Priest"}
};